# 1.numpy入门

In [3]:
# 导包
import numpy as np

# 基于 Python的列表, 构建: numpy对象.
#  np.array()
arr = np.array([1, 2, 3, 4, 5])
#打印数据
print(arr)
#打印类型
print(arr.dtype)

[1 2 3 4 5]
int64


# 2.numpy的属性

In [15]:
# 1. 构建1个3行5列的 ndarray对象(n维数字), 即: 3行5列.
# 语法： .arange(xx).reshape((xx, xx))
arr = np.arange(15).reshape((3,5))
#维度 .shape
print(arr.shape)
#轴:.ndim,几维数组, 维度(轴)就是几
print(arr.ndim)
#长度：.size
print(arr.size)
#元素的类型:.dtype
print(arr.dtype)
#大小(字节数):.itemsize
print(arr.itemsize)
#数组的类型:type(arr)
type(arr)
arr.itemsize

(3, 5)
2
15
int64
8


8

In [ ]:
# 扩展: 上述的 shape, ndim, size等属性, 可以改写成: np.属性名(对象对)的形式. 
# 例如：np.shape(arr)


# 3.创建ndarray对象

## 3.1把Python列表封装成ndarray对象

In [ ]:
# int数组
arr1 = np.array([1, 2, 3, 4, 5])

#数组对象打印
print(arr1)
#数组类型: type(xx)
print(type(arr1))
#数组元素类型:.dtype
print(arr1.dtype)

In [ ]:
# float数组
arr11=np.ones((2, 3)).dtype(np.float64)
#数组对象
print(arr11)
#数组类型
print(type(arr11))
#数组元素类型
print(arr11.dtype)

## 3.2 zeros()/ones()/empty() 函数创建 ndarray对象

In [ ]:
# zeros() 创建全是0的数组, 即: ndarray对象
#np.zeros((x, x))
#获取：2行3列

#数组对象

#数组类型

#数组元素类型

In [ ]:
# ones() 创建全是1的数组, 即: ndarray对象
#np.ones((x,x))

#数组对象

#数组类型

#数组元素类型

In [ ]:
# empty() 创建内容随机, 且依赖内存状态的随机值, 即: ndarray对象
# np.empty((x, x))


#数组对象

#数组类型

#数组元素类型


## 3.3 arange()函数, 创建ndarray对象

In [ ]:
# arange(起始值, 结束值, 步长, 类型), 它类似于Python中的 range()
# 类型： （类型）dtype=np.xxx
arr6 = np.arange(-1,10,2,dtype= float)
print(type(arr6))

#数组对象

#数组类型

#数组元素类型


## 3.4 matrix() 生成二维数组

In [ ]:
# matrix()属于ndarry的子集, 生成 二维数组的. 
#np.matrix([[x, x, x], [x, x, x]])

#数组对象

#数组类型

#数组元素类型


## 3.5 rand(), randint(), uniform() 生成ndarray对象

In [ ]:
# rand(), 生成0.0 ~ 1.0之间的 随机数组. 包左不包右.
# np.random.rand(xx,xx)
# 2行3列


#数组对象

#数组类型

#数组元素类型

In [ ]:
# randint(), 生成指定范围之间的 随机数组. 包左不包右.
#np.random.randint(xx,xx, size=(xx,xx))


#数组对象

#数组类型

#数组元素类型


In [ ]:
# uniform(), 生成指定范围之间的 随机数组. 包左不包右.
#np.random.uniform(xx, xx, size=(xx, xx))

#数组对象

#数组类型

#数组元素类型


## 3.6 通过 astype()函数, 把ndarray => ndarray

In [ ]:
# 1. 创建1个 float类型的 数组.
arr11 = np.ones((2, 3), dtype=np.float32)  # 2行3列
print(f'数组对象: {arr11}')  # [[1. 1. 1.]   [1. 1. 1.]]
print(f'数组类型: {type(arr11)}')  # <class 'numpy.ndarray'>
print(f'数组元素类型: {arr11.dtype}')  # float32

In [36]:
# 2. 把 arr11的元素类型, 从 float32 => int64
# 语法： xx.astype(np.int64)
arr11 = np.array([1.1, 2.0, 3.0, 4.0, 5.0],dtype=np.float32)
arr11 = arr11.astype(np.int64)
#数组对象
print(arr11)
#数组类型
print(type(arr11))
#数组元素类型
print(arr11.dtype)

[1 2 3 4 5]
<class 'numpy.ndarray'>
int64


## 3.7 logspace()等比数列 和 linspace()等差数列

In [19]:
# logspace(起始幂值, 结束幂值, 元素个数, base=底数)   生成10^起始幂值 ~ 10^结束幂值范围内的, 指定个数的数据, 底数默认是10, 可以自定义
# 语法： np.logspace(x,x,x,x)
# 1.创建：10^0 ~ 10^5之间, 10个元素, 等比数列
arr=np.logspace(0, 5, 10, base=2)
# 1.创建：2^0 ~ 2^5之间,  10个元素, 等比数列
arr1=np.logspace(2, 5, 10, base=2)
#数组对象
print(arr)
#数组类型
print(type(arr))
#数组元素类型
print(arr.dtype)

[ 1.          1.46973449  2.16011948  3.1748021   4.66611616  6.85795186
 10.0793684  14.8139954  21.77264    32.        ]


In [22]:
# linspace(起始值, 结束值, 元素个数, endpoint=True|False)   生成起始值 ~ 结束值之间的, 指定元素个数的值, 等差数列, endpoint=True(默认), 包含结束值. False:不包含
#1.创建： 0 ~ 5之间, 5个数, 等差数列,  endpoint=True(默认值)
arr=np.linspace(0, 5, 5, endpoint=False)

#数组对象
print(arr)
#数组类型
print(type(arr))
#数组元素类型
print(arr.dtype)

[0. 1. 2. 3. 4.]


# 4. Numpy的内置函数

## 4.1 内置函数之 基本函数

In [51]:
# 基本函数如下: ceil(), floor(), rint(), isnan(), abs(), multiply(), divide(), where()
# np.ceil(): 向上最接近的整数，参数是 number 或 array
# np.floor(): 向下最接近的整数，参数是 number 或 array
# np.rint(): 四舍五入，参数是 number 或 array
# np.isnan(): 判断元素是否为 NaN(Not a Number)，参数是 number 或 array
# np.multiply(): 元素相乘，参数是 number 或 array
# np.divide(): 元素相除，参数是 number 或 array
# np.abs()：元素的绝对值，参数是 number 或 array
# np.where(condition, x, y): 三元运算符，x if condition else y
# 注意: 需要注意multiply/divide 如果是两个ndarray进行运算 shape必须一致

# 1. 生成ndarray对象.
# 获取1个标准的正态分布的 2行3列的数据. 
# 语法：np.random.randn(x, x)
arr = np.random.randn(2, 3)
# 2. 演示函数.
print(f'数组对象: {arr}')
np.ceil(arr)
np.floor(arr)
np.rint(arr)
np.isnan(arr)
np.multiply(arr, 2)
np.divide(arr, 2)
np.abs(arr)
np.where(arr > 0, arr, 0)

数组对象: [[ 0.69823202 -0.43959253  1.82645714]
 [-0.71509976  0.07216007 -0.38988977]]


array([[0.69823202, 0.        , 1.82645714],
       [0.        , 0.07216007, 0.        ]])

## 4.2 内置函数之 统计函数

In [55]:
# 统计函数介绍
# np.mean(), np.sum()：所有元素的平均值，所有元素的和，参数是 number 或 array
# np.max(), np.min()：所有元素的最大值，所有元素的最小值，参数是 number 或 array
# np.std(), np.var()：所有元素的标准差，所有元素的方差，参数是 number 或 array
# np.argmax(), np.argmin()：最大值的下标索引值，最小值的下标索引值，参数是 number 或 array
# np.cumsum(), np.cumprod()：返回一个一维数组，每个元素都是之前所有元素的 累加和 和 累乘积，参数是 number 或 array
# 多维数组默认统计全部维度，axis参数可以按指定轴心统计，值为0则按列统计，值为1则按行统计。

# 1. 生成1个ndarray对象
# 创建数组：3行4列
# 语法：  np.arange(x).reshape((x, x)) 
arr=np.arange(12).reshape((3,4))

# 2. 演示 cumsum(), 累加和.
np.cumsum(arr)
# 3. 演示 sum()求和.
np.sum(arr)


np.int64(66)

# 4.3 内置函数之 比较函数

In [58]:
# any()   任意1个元素满足即可, 返回True, 否则返回False
# all()   所有元素都要满足, 返回True, 否则返回False
# 1. 生成1个数列.
# 创建：2行3列的 正态分布的数据.
# 语法：np.random.randn(x, x)
arr=np.arange(6).reshape(2,3)

# np.any(x>>0)： 只要arr的任意1个元素大于0即可.    True 
np.any(arr>0)
# np.all(x>0)： arr的所有元素都要大于0即可.       False
np.all(arr>1)

np.False_

## 4.4 内置函数之 排序函数

In [59]:
# 方式1: np.sort(arr)     排序, 并返回新的副本.
# 方式2: arr.sort()       对原数组排序.

# 1. 获取ndarray对象
arr = np.array([1, 5, 3, 2, 6])
print(f'排序前: {arr}')
# arr.sort()

# 2. 排序
arr.sort()
# 3. 排序后
arr

排序前: [1 5 3 2 6]


array([1, 2, 3, 5, 6])

## 4.5 内置函数之 去重函数

In [61]:
# unique(): 去重函数, 类似于Python的 set()集合.

# 1. 创建ndarray对象
# 语法：np.array([x,x,x])
# [[1, 2, 1, 6], [1, 3, 2, 5]]
arr=np.array([1, 2, 1, 6, 1, 3, 2, 5])
# 2. 去重.
np.unique(arr)
# 3. 打印结果.
print(
np.unique(arr)
)

[1 2 3 5 6]


# 5. Numpy运算

## 5.1 基本运算, 即: 对应元素直接运算即可.

In [63]:
# 1. 创建两个ndarray对象.
arr1 = np.array([10, 20, 30, 40])       # [10, 20, 30, 40]
arr2 = np.arange(4)                     # [0, 1, 2, 3]

# 2. 基本运算, 对应元素运算的.
#2.1 加法
np.add(arr1, arr2)
#2.1 乘法：方法一：*； 方法二：np.multiply（x,x）
print(arr1 * arr2)
np.multiply(arr1, arr2)

# 3. 打印结果.
print(np.multiply(arr1, arr2))

[  0  20  60 120]
[  0  20  60 120]


## 5.2 矩阵运算, 情况1: 行列数一致

In [65]:
# 1. 创建两个ndarray对象, 二维的, 更好的演示 矩阵运算.
arr1 = np.array([[1, 2, 3], [4, 5, 6]])       # [[1, 2, 3], [4, 5, 6]]
arr2 = np.array([[1, 2, 3], [4, 5, 6]])       # [[1, 2, 3], [4, 5, 6]]

# 2. 基本运算, 对应元素运算的.
#乘法
np.multiply(arr1, arr2)
# 3. 打印结果.
print(np.multiply(arr1, arr2))


[[ 1  4  9]
 [16 25 36]]


## 5.3 矩阵运算, 情况2: 行列数相反

In [67]:
# dot()函数, 适用于: 行列数相反的情况. 
# 1. 创建两个ndarray对象, 二维的, 更好的演示 矩阵运算.
#语法： np.array（[[x,x],[x,x]]）
#创建：2行3列
arr=np.arange(6).reshape(2,3)
#创建：3行2列
arr1=np.arange(6).reshape(3,2)

# 2. 基本运算, 对应元素运算的.
#语法： x.dot(x)
arr.dot(arr1)

# 3. 打印结果.
print(arr.dot(arr1))

[[10 13]
 [28 40]]
